version: "3.9"

services:
    db:
        image: mysql
        container_name: DataBase1
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: NashiroDEV
            MYSQL_PASSWORD: temp

    phpmyadmin:
        image: phpmyadmin
        container_name: PhpMyAdmin3
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8000:80
        environment:
            PMA_HOST: db

    web:
        build: php
        container_name: LiblockPHP
        restart: on-failure
        volumes:
            - ./app:/app:rw
        ports:
            - 8080:80

volumes:
    db-data:
